import React from "react"

import TenancyDoughnut from "@/components/Dashboard/TenancyDoughnut"

const TenantTabChart = () => {
	/*
	 * Graph Data
	 */

	var dashboard = {
		units: {
			totalOccupied: 55,
			totalUnoccupied: 2,
			percentage: "96.5",
			list: [
				{
					id: 82,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "Lesley Dunlap",
					rent: "0",
					deposit: "0",
					serviceCharge: {
						garbage: 11722,
						parking: 8602,
						service: 10888,
						cleaning: 19090,
						internet: 2477,
						security: 6225,
						electricity: 16951,
					},
					type: "apartment",
					bedrooms: 1,
					size: {
						value: "33",
					},
					ensuite: 26,
					dsq: 1,
					status: "vacant",
					tenantId: null,
					tenantAvatar: null,
					tenantName: null,
					tenantEmail: null,
					tenantPhone: null,
					tenantGender: null,
					tenantOccupiedAt: null,
					currentUserUnitId: null,
				},
				{
					id: 81,
					propertyId: 1,
					propertyName: "Kulas Alley",
					name: "Noelle Gardner",
					rent: "10,000",
					deposit: "20,000",
					serviceCharge: {
						garbage: 16328,
						parking: 2858,
						service: 9295,
						cleaning: 10616,
						internet: 19712,
						security: 8220,
						electricity: 17207,
					},
					type: "shop",
					bedrooms: null,
					size: {
						unit: "m²",
						value: "37",
					},
					ensuite: 27,
					dsq: 1,
					status: "vacant",
					tenantId: null,
					tenantAvatar: null,
					tenantName: null,
					tenantEmail: null,
					tenantPhone: null,
					tenantGender: null,
					tenantOccupiedAt: null,
					currentUserUnitId: null,
				},
				{
					id: 55,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "G16",
					rent: "37,000",
					deposit: "28,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 2,
					size: null,
					ensuite: 3,
					dsq: 1,
					status: "occupied",
					tenantId: 51,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Dr. Obie Cruickshank III",
					tenantEmail: "kenny.schumm@example.net",
					tenantPhone: "458.706.6703",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 215,
				},
				{
					id: 54,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "F5",
					rent: "31,000",
					deposit: "52,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 3,
					size: null,
					ensuite: 0,
					dsq: 1,
					status: "occupied",
					tenantId: 46,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Kayley Blick",
					tenantEmail: "mante.alfredo@example.com",
					tenantPhone: "1-319-363-7678",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 211,
				},
				{
					id: 53,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "F2",
					rent: "70,000",
					deposit: "202,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 5,
					size: null,
					ensuite: 2,
					dsq: 1,
					status: "occupied",
					tenantId: 5,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Dr. Justyn Pacocha",
					tenantEmail: "xanderson@example.net",
					tenantPhone: "+1-716-608-1629",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 208,
				},
				{
					id: 52,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "A7",
					rent: "97,000",
					deposit: "20,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 1,
					size: null,
					ensuite: 1,
					dsq: 0,
					status: "occupied",
					tenantId: 5,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Dr. Justyn Pacocha",
					tenantEmail: "xanderson@example.net",
					tenantPhone: "+1-716-608-1629",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 205,
				},
				{
					id: 51,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "F15",
					rent: "69,000",
					deposit: "192,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 2,
					size: null,
					ensuite: 2,
					dsq: 1,
					status: "occupied",
					tenantId: 16,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Elizabeth McKenzie II",
					tenantEmail: "bettye93@example.net",
					tenantPhone: "+1-484-888-3902",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 201,
				},
				{
					id: 50,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "E6",
					rent: "11,000",
					deposit: "194,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 1,
					size: null,
					ensuite: 0,
					dsq: 0,
					status: "occupied",
					tenantId: 34,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Yvette Boehm",
					tenantEmail: "narciso41@example.net",
					tenantPhone: "505-228-2450",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 197,
				},
				{
					id: 49,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "E4",
					rent: "36,000",
					deposit: "190,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 2,
					size: null,
					ensuite: 1,
					dsq: 1,
					status: "occupied",
					tenantId: 44,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Mr. Philip Jacobson Sr.",
					tenantEmail: "bode.dino@example.net",
					tenantPhone: "843.865.6333",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 192,
				},
				{
					id: 48,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "C17",
					rent: "69,000",
					deposit: "136,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 2,
					size: null,
					ensuite: 1,
					dsq: 0,
					status: "occupied",
					tenantId: 41,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Zane Reichert",
					tenantEmail: "raynor.flavio@example.com",
					tenantPhone: "+1-959-265-9781",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 188,
				},
				{
					id: 47,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "G20",
					rent: "53,000",
					deposit: "50,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 5,
					size: null,
					ensuite: 3,
					dsq: 1,
					status: "occupied",
					tenantId: 38,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Quinn Kris",
					tenantEmail: "zena.lang@example.com",
					tenantPhone: "+1-865-295-0094",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 185,
				},
				{
					id: 46,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "C10",
					rent: "79,000",
					deposit: "138,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 4,
					size: null,
					ensuite: 3,
					dsq: 0,
					status: "occupied",
					tenantId: 20,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Mrs. Vergie Schroeder III",
					tenantEmail: "ugoldner@example.net",
					tenantPhone: "(352) 731-4990",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 181,
				},
				{
					id: 45,
					propertyId: 5,
					propertyName: "Pouros Center",
					name: "E4",
					rent: "43,000",
					deposit: "58,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 3,
					size: null,
					ensuite: 3,
					dsq: 1,
					status: "occupied",
					tenantId: 23,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Dr. Antone Kutch",
					tenantEmail: "margarita86@example.com",
					tenantPhone: "+1.225.323.5084",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 177,
				},
				{
					id: 44,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "D6",
					rent: "39,000",
					deposit: "156,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 1,
					size: null,
					ensuite: 1,
					dsq: 0,
					status: "occupied",
					tenantId: 11,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Prof. Noemi Jast Jr.",
					tenantEmail: "jasmin07@example.net",
					tenantPhone: "+1-650-667-5105",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 174,
				},
				{
					id: 43,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "E12",
					rent: "48,000",
					deposit: "54,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 2,
					size: null,
					ensuite: 2,
					dsq: 0,
					status: "occupied",
					tenantId: 13,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Dr. Justus Johns",
					tenantEmail: "estell.grimes@example.com",
					tenantPhone: "+1.240.462.7713",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 169,
				},
				{
					id: 42,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "F8",
					rent: "73,000",
					deposit: "50,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 3,
					size: null,
					ensuite: 0,
					dsq: 0,
					status: "occupied",
					tenantId: 37,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Callie Bernhard",
					tenantEmail: "kirlin.brady@example.net",
					tenantPhone: "+1-281-469-4512",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 164,
				},
				{
					id: 41,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "F13",
					rent: "97,000",
					deposit: "144,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 3,
					size: null,
					ensuite: 1,
					dsq: 0,
					status: "occupied",
					tenantId: 4,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Wanjiku Muhandi",
					tenantEmail: "cikumuhandi@gmail.com",
					tenantPhone: "0721721357",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 161,
				},
				{
					id: 40,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "F14",
					rent: "10,000",
					deposit: "34,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 3,
					size: null,
					ensuite: 2,
					dsq: 0,
					status: "occupied",
					tenantId: 31,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Rashad Spencer",
					tenantEmail: "wilson68@example.com",
					tenantPhone: "785-225-4358",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 156,
				},
				{
					id: 39,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "E5",
					rent: "13,000",
					deposit: "78,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 4,
					size: null,
					ensuite: 2,
					dsq: 0,
					status: "occupied",
					tenantId: 2,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Super Admin",
					tenantEmail: "al@black.co.ke",
					tenantPhone: "832.282.6271",
					tenantGender: "male",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 151,
				},
				{
					id: 38,
					propertyId: 4,
					propertyName: "Kozey Oval",
					name: "D0",
					rent: "93,000",
					deposit: "48,000",
					serviceCharge: null,
					type: "apartment",
					bedrooms: 2,
					size: null,
					ensuite: 3,
					dsq: 0,
					status: "occupied",
					tenantId: 29,
					tenantAvatar: "/storage/avatars/male-avatar.png",
					tenantName: "Gerard Nicolas",
					tenantEmail: "anissa13@example.org",
					tenantPhone: "478-391-0540",
					tenantGender: "female",
					tenantOccupiedAt: "01 Aug 2025",
					currentUserUnitId: 147,
				},
			],
			tenantsThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [0, 0, 0, 14, 53, 94, 110, 110, 55, 55, 0, 0],
			},
			vacanciesThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [57, 57, 57, 43, 4, -37, -53, -53, 2, 2, 0, 0],
			},
		},
		rent: {
			paid: 57952000,
			due: 6305000,
			total: "64,257,000",
			percentage: "90.2",
			paidThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [
					2420000, 2420000, 2420000, 2420000, 3055000, 4840000, 7806000,
					10857000, 10857000, 10857000, 0, 0,
				],
			},
			unpaidThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [
					561000, 561000, 561000, 561000, 601000, 722000, 737000, 667000,
					667000, 667000, 0, 0,
				],
			},
		},
		water: {
			paid: 69682.02000000012,
			due: 7044.730000000002,
			total: "76,727",
			usageTwoMonthsAgo: "5014",
			usageLastMonth: 0,
			percentage: "90.8",
			paidThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [
					7554.12, 6632.5300000000025, 5747.760000000002, 5007.559999999999,
					5458.74, 8094.449999999999, 9800.559999999998, 11764.96000000002,
					6697.179999999988, 2924.1599999999976, 0, 0,
				],
			},
			unpaidThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [
					1279.95, 1167.5399999999997, 943.9200000000002, 865.7199999999998,
					808.93, 628.6, 519.4, 450.1099999999999, 265.71999999999997,
					114.84000000000002, 0, 0,
				],
			},
		},
		serviceCharge: {
			paid: 9987869,
			due: 929500,
			total: "10,917,369",
			percentage: "91.5",
			paidThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [
					400070, 400070, 400070, 400070, 529214, 881447, 1374467, 1867487,
					1867487, 1867487, 0, 0,
				],
			},
			unpaidThisYear: {
				labels: [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December",
				],
				data: [
					92950, 92950, 92950, 92950, 92950, 92950, 92950, 92950, 92950, 92950,
					0, 0,
				],
			},
		},
	}

	var dashboardProperties = {
		total: 5,
		ids: [1, 2, 3, 4, 5],
		names: [
			"Kulas Alley",
			"Nathanial Trail",
			"Bechtelar Forge",
			"Kozey Oval",
			"Pouros Center",
		],
		units: [12, 11, 11, 12, 11],
	}

	return (
		<div className="card border shadow-sm p-4">
			<div className="card border shadow-sm text-center p-4">
				{/* Tenancy Doughnut */}
				<TenancyDoughnut
					dashboard={dashboard}
					dashboardProperties={dashboardProperties}
				/>
				{/* Tenancy Doughnut End */}
			</div>
		</div>
	)
}

export default TenantTabChart